services:
  hamradio:
    build: .
    container_name: hamradio
    restart: unless-stopped
    privileged: true
    ports:
      - "8090:8090"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    environment:
      TZ: Europe/Istanbul
      HAM_FREQ: "145.500M"
      HAM_MODE: "fm"
    tmpfs:
      - /tmp
