devices: ({
    type = "rtlsdr";
    index = 0;
    gain = 38;
    centerfreq = 127.5;
    correction = 0;
    channels: (
        {
            freq = 121.500;
            modulation = "am";
            outputs: ({
                type = "icecast";
                server = "127.0.0.1";
                port = 8000;
                mountpoint = "emergency";
                name = "Acil Durum";
                genre = "Aviation";
                username = "source";
                password = "hackme";
            });
        },
        {
            freq = 118.100;
            modulation = "am";
            outputs: ({
                type = "icecast";
                server = "127.0.0.1";
                port = 8000;
                mountpoint = "tower";
                name = "Istanbul Kule";
                genre = "Aviation";
                username = "source";
                password = "hackme";
            });
        },
        {
            freq = 120.900;
            modulation = "am";
            outputs: ({
                type = "icecast";
                server = "127.0.0.1";
                port = 8000;
                mountpoint = "approach";
                name = "Istanbul Yaklasma";
                genre = "Aviation";
                username = "source";
                password = "hackme";
            });
        },
        {
            freq = 119.100;
            modulation = "am";
            outputs: ({
                type = "icecast";
                server = "127.0.0.1";
                port = 8000;
                mountpoint = "ground";
                name = "Istanbul Yer";
                genre = "Aviation";
                username = "source";
                password = "hackme";
            });
        }
    );
});
