[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:icecast]
command=/usr/bin/icecast2 -c /etc/icecast2/icecast.xml
user=icecast2
priority=10
autostart=true
autorestart=true
stdout_logfile=/var/log/icecast_stdout.log
stderr_logfile=/var/log/icecast_stderr.log

[program:rtl_airband]
command=/usr/local/bin/rtl_airband -f -c /usr/local/etc/rtl_airband.conf
priority=20
startsecs=3
autostart=true
autorestart=true
stdout_logfile=/var/log/rtl_airband_stdout.log
stderr_logfile=/var/log/rtl_airband_stderr.log

[program:nginx]
command=/usr/sbin/nginx
priority=30
autostart=true
autorestart=true
stdout_logfile=/var/log/nginx_stdout.log
stderr_logfile=/var/log/nginx_stderr.log
