[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log

[program:pulseaudio]
command=/usr/bin/pulseaudio --daemonize=no --disallow-exit --exit-idle-time=-1 --log-level=warning
autorestart=true
priority=5

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autorestart=true
priority=10

[program:xvfb]
command=/usr/bin/Xvfb :99 -screen 0 %(ENV_SCREEN_WIDTH)sx%(ENV_SCREEN_HEIGHT)sx24
autorestart=true
priority=15

[program:sdrpp]
command=/usr/bin/sdrpp
environment=DISPLAY=":99"
autorestart=true
priority=20
startsecs=3

[program:x11vnc]
command=/usr/bin/x11vnc -display :99 -forever -nopw -shared -rfbport 5900
autorestart=true
priority=30
startsecs=2

[program:websockify_vnc]
command=/usr/bin/websockify 8091 localhost:5900
autorestart=true
priority=40
startsecs=2

[program:audio_bridge]
command=/usr/bin/python3 /opt/audio_bridge.py
autorestart=true
priority=50
startsecs=3
