[server]
port=9002
html_root="html-svelte/dist/"
otherusers=1
title="PhantomSDR - 145 MHz VHF"

[input]
sps=2880000
fft_size=131072
frequency=145000000
signal="iq"
accelerator="none"
audio_sps=12000

[input.driver]
name="stdin"
format="u8"

[input.defaults]
frequency=145500000
modulation="FM"
