[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:xvfb]
command=Xvfb :99 -screen 0 1280x720x24 -ac
autorestart=true
priority=10

[program:pulseaudio]
command=/usr/bin/pulseaudio --daemonize=no --disallow-exit --exit-idle-time=-1 --log-level=warning
autorestart=true
priority=15

[program:sdrtrunk]
command=/opt/start-sdrtrunk.sh
environment=DISPLAY=":99"
autorestart=true
priority=30
startsecs=5

[program:x11vnc]
command=x11vnc -display :99 -forever -shared -nopw -wait 50 -defer 50 -rfbport 5900
autorestart=true
priority=40

[program:websockify]
command=websockify --web=/usr/share/novnc 8090 localhost:5900
autorestart=true
priority=50
